version: '3'
services:
  redis:
    image: redis:alpine
    container_name: fast_feet_redis
    restart: always
    ports:
      - '6379:6379'

  db:
    image: postgres
    container_name: fast_feet_postgres
    restart: always
    environment:
      POSTGRES_DB: fastfeet
      POSTGRES_PASSWORD: docker
    ports:
      - '5434:5432'
